apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod1
spec:
  restartPolicy: Never
  containers:
    - name: cuda-container
      image: quay.io/marhatha/togopool:v17
  imagePullSecrets:
    - name: marhatha-llama-pull-secret
      nodeSelector:
        run: ai
      resources:
        requests:
          memory: "40Gi"
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
          memory: "40Gi"
